### ISSUE TITLE
Could not scan and connect the available devices on many Mobile devices

### ISSUE THREAD

**Issue by prakharGargIbirds** [pauldemarco/flutter_blue#644]
The example given by the flutter_blue team is not running on many devices but running on some devices. The permissions are given fully but still, the app is not able to discover available devices, and if it can't scan, how it will show the available devices on the list, also I'm not able to discover the currently connected BLE device to my mobile Bluetooth and all these issues I'm facing in the android.
![2020-08-04](https://user-images.githubusercontent.com/68417742/89309345-ee4ed580-d690-11ea-98c1-b94dcd6b575f.jpg)
![2020-08-04 (1)](https://user-images.githubusercontent.com/68417742/89309391-00307880-d691-11ea-9f7c-68ae9a7c8ab7.jpg)

**Comment by calvinsug** [comment]
I also face the exactly same situation for this, have you solved this issue ?

**Comment by prakharGargIbirds** [comment]
> I also face the exactly same situation for this, after start scanning, the result is always 0 device founds.
> Have you solved this issue ?

The issue was resolved automatically after updating the package. Please try to update the package.

**Comment by calvinsug** [comment]
i think i have already used the latest version (0.7.2), but still facing this issue
